version: 2
project_name: rscli

before:
  hooks:
    - go mod tidy

archives:
  - id: default
    formats: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

homebrew_casks:
  - name: rscli
    repository:
      owner: reysys-technology
      name: homebrew-tap
      pull_request:
        enabled: true

    homepage: https://github.com/reysys-technology/rscli
    description: Reysys CLI

    commit_author:
      name: goreleaser-bot
      email: support@reysys.com
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
          end

builds:
  - id: default
    binary: rscli
    main: ./cmd/rscli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -extldflags "-static"
      - -X main.version={{.Version}}
    flags:
      - -trimpath
    tags:
      - netgo
      - osusergo
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows

nfpms:
  - id: default
    package_name: rscli
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Reysys Technology
    homepage: https://github.com/reysys-technology/rscli
    maintainer: Reysys <support@reysys.com>
    description: Reysys CLI
    license: Apache-2.0
    formats:
      - apk
      - deb
      - rpm

changelog: { }

release:
  draft: true
  replace_existing_draft: true
