version: 2
project_name: rscli

before:
  hooks:
    - go mod tidy

archives:
  - format: binary

builds:
  - id: rscli
    binary: rscli
    main: ./cmd/cli
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows

changelog: { }

release: { }
