version: 2
project_name: rscli

before:
  hooks:
    - go mod tidy

archives:
  - id: default
    formats: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
builds:
  - id: rscli
    binary: rscli
    main: ./cmd/cli
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows

changelog: { }

release: { }
