version: 2
project_name: rscli

before:
  hooks:
    - go mod tidy

archives:
  - formats: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

dockers_v2:
  - images:
      - ghcr.io/reysys-technology/rscli
      - reysys/rscli
    tags:
      -  latest
      - "{{ .Major }}"
      - "{{ .Version }}"

furies:
  - account: reysys

homebrew_casks:
  - name: rscli
    alternative_names:
      - "rscli@{{ .Major }}"
      - "rscli@{{ .Version }}"
    repository:
      owner: reysys-technology
      name: homebrew-tap
      branch: "{{ .ProjectName }}-{{ .Version }}"
      pull_request:
        enabled: true
        base:
          owner: reysys-technology
          name: homebrew-tap
          branch: main

    homepage: https://github.com/reysys-technology/rscli
    description: Reysys CLI

    commit_author:
      name: goreleaser-bot
      email: support@reysys.com
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
          end

builds:
  - binary: rscli
    main: ./cmd/rscli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -extldflags "-static"
    flags:
      - -trimpath
    tags:
      - netgo
      - osusergo
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows

nfpms:
  - package_name: rscli
    vendor: Reysys Technology
    homepage: https://github.com/reysys-technology/rscli
    maintainer: reysys <support@reysys.com>
    description: Reysys CLI
    license: Apache-2.0
    file_name_template: '{{ .PackageName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    formats:
      - apk
      - deb
      - rpm
    apk:
      signature:
        key_file: /tmp/rsa.key
    deb:
      signature:
        key_file: /tmp/gpg.key
    rpm:
      signature:
        key_file: /tmp/gpg.key

changelog: { }

release:
  draft: true
  replace_existing_draft: true
