version: 2
project_name: rscli

before:
  hooks:
    - go mod tidy

archives:
  - id: default
    formats: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

builds:
  - id: rscli
    binary: rscli
    main: ./cmd/cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -extldflags "-static"
    flags:
      - -trimpath
    tags:
      - netgo
      - osusergo
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows

changelog: { }

release: { }
